version: '3.4'

services:
  db:
    container_name: dbot-db
    image: "postgres:13.1-alpine"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
  # nodejs:
  #   build:
  #     context: .
  #     target: dbot-twitchbot
  #   container_name: dbot-node
  #   depends_on:
  #     - db
