apiVersion: v1
kind: ConfigMap
metadata:
  name: twitchbot-config
  namespace: twitchbot
  labels:
    app: twitchbot
data:
  POSTGRES_DB: twitchbot
  POSTGRES_USER: twitchbot
  POSTGRES_HOST: twitchbot-postgresql.twitchbot.svc.cluster.local
  POSTGRES_PORT: "5432"
  USE_MQ: "true"
  MQ_PORT: "5672"
  MQ_UI_PORT: "15671"