---
apiVersion: v1
kind: Service
metadata:
  name: twitchbot
  namespace: twitchbot
  labels:
    app: twitchbot
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: twitchbot
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitchbot
  namespace: twitchbot
  labels:
    app: twitchbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitchbot
  template:
    metadata:
      labels:
        app: twitchbot
    spec:
      containers:
      - name: twitchbot
        image: dbot-twitchbot:latest
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: twitchbot-config
          - secretRef:
              name: twitchbot-secrets



